spring:
  datasource:
    url: jdbc:h2:file:~/rescue-me
    driver-class-name: org.h2.Driver
    username: sa
    password: ''
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2

axon:
  serializer:
    general: jackson
  axonserver:
    port: 8024
    hostname: localhost