name: Build rescue me dog service

on:
  push:
    branches:
      - master
      - feature/pipeline-creation

jobs:
  pre-test:
    name: Unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Maven package
        run: mvn -B clean package
      - name: Maven verify
        run: mvn -B clean verify

  artifact:
    name: Publish Artifact
    runs-on: ubuntu-latest
    needs:
      - pre-test
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-publish-image:
    name: Publish docker Image
    runs-on: ubuntu-latest
    needs:
      - pre-test
      - artifact
    env:
      REPO: ${{ secrets.DOCKER_REPO_DOGS }}
    steps:
      - uses: actions/checkout@v1
      - name: Dockerhub login
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Building Docker Image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_RUN_ID} .
      - name: Publish Docker Image
        run: docker push $REPO