name: Build rescue me dog service

on:
  push:
    branches:
      - master
      - feature/pipeline-creation

jobs:
  pre-test:
    name: Unit-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Maven package
        run: mvn -B clean package
      - name: Maven verify
        run: mvn -B clean verify

  artifact:
    name: Publish Artifact
    runs-on: ubuntu-latest
    needs:
      - pre-test
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Publish artifact on GitHub Packages
        run: mvn -B clean deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  docker:
    runs-on: ubuntu-latest
    needs:
      - pre-test
      - artifact
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        env:
          REPO: ${{ secrets.DOCKER_REPO_DOGS }}
        with:
          context: .
          push: true
          tags: ${REPO}:latest,${REPO}:${GITHUB_RUN_ID}